### ISSUE TITLE
Overall training code

### ISSUE THREAD

**Issue by xiaoyudanaa** [brandleyzhou/SUB-Depth#1]
I am very honored to read such an innovative article. I would like to use your network in my personal project, could you please post the complete code

**Comment by brandleyzhou** [comment]
Thanks for your interest. You can first download monodepth2, and replace the corresponding file/folders with ones in this repo.

**Comment by xiaoyudanaa** [comment]
> Thanks for your interest. You can first download monodepth2, and replace the corresponding file/folders with ones in this repo.
I'm very glad you can reply to me. I downloaded the project, but I didn't find the UncertDecoder in trainer.py. Some configurations in trainer are different from monodepth2. My coding skills are not very good. If it is convenient for you, I look forward to your sending me a complete project, my email is 1529712268@qq.com. Thank you very much

**Comment by brandleyzhou** [comment]
As the original code is not well documented, I only upload the selected partitions. I have uploaded the missing UncertDecoder to networks/. hope it helps.

**Comment by xiaoyudanaa** [comment]
> As the original code is not well documented, I only upload the selected partitions. I have uploaded the missing UncertDecoder to networks/. hope it helps.

After reading the trainer.py code, I found that your repo has the relevant code to call adam.pth, but adam.pth is not generated during training.

**Comment by xiaoyudanaa** [comment]
I also want to ask if evaluate_depth.py is the same as monodepth2. This picture is generated by the weight_10 test, the network does not seem to converge
![image](https://user-images.githubusercontent.com/77732714/164402243-2e663286-3108-477f-90b0-a602b97e5351.png)

**Comment by brandleyzhou** [comment]
Yep, it's the same. and did you use the weights from monodepth2 to initialize the teacher net? and the test ads rel is?  and how did you get this depth map? it's quite different from ones that are using test_simple.py in monodepth2.

**Comment by xiaoyudanaa** [comment]
“use the weights from monodepth2 to initialize the teacher net”.what does it mean here？
I don't know what "self.opt.teacher_weights_folder" refers to, which doesn't have this in monodepth2. So I commented this part out. what should i do
![image](https://user-images.githubusercontent.com/77732714/164729907-b5bb5f86-c024-4510-8d46-c12df8420cbb.png)

**Comment by brandleyzhou** [comment]
you need all of these you have commented out to load teacher .pth files which are from monodepth2 trained models

**Comment by xiaoyudanaa** [comment]
> you need all of these you have commented out to load teacher .pth files which are from monodepth2 trained models

"teacher .pth files which are from monodepth2 trained models"。I would like to ask what exactly this pth file refers to. Do I have to train the original monodepth2 first to get the encoder.pth and decoder.pth files of weight_19?

**Comment by brandleyzhou** [comment]
yes, the teacher weights are necessary.. but I suggest you directly download the well-trained weights from monodepth2's repo

**Comment by xiaoyudanaa** [comment]
I modified the decoder side of monodepth2. Is it also possible to use the original pretrained weights of monodepth2 directly?

**Comment by brandleyzhou** [comment]
For the teacher net, you can use the original monodepth2 networks. but you can modify the student depth net.
otherwise, you have to train your modified teacher model first.

**Comment by xiaoyudanaa** [comment]
Thank you very much for your patient reply. I have one last question, do UncertDecoder and DepthDecoder have to be consistent? I modified the DepthDecoder, does the UncertDecoder need to do the same?

**Comment by brandleyzhou** [comment]
No, using two different architectures for them is ok as well.
